In [1]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

# enter the foldername in your Drive where you have saved the unzipped
# 'cs231n' folder containing the '.py', 'classifiers' and 'datasets'
# folders.
# e.g. 'cs231n/assignments/assignment1/cs231n/'
FOLDERNAME = 'cs224n/assignments/a4'

assert FOLDERNAME is not None, "[!] Enter the foldername."



Mounted at /content/drive


In [2]:
import sys
sys.path.append('/content/drive/My Drive/{}'.format(FOLDERNAME))
%cd ../content/drive/MyDrive/cs224n/assignments/a4/

/content/drive/MyDrive/cs224n/assignments/a4


In [3]:
!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh

!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh

!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local

sys.path.append('/usr/local/lib/python3.6/site-packages')

--2021-05-08 03:06:15--  https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh [following]
--2021-05-08 03:06:15--  https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

PREFIX=/usr/local
installing: python-3.6.4-hc3d631a_1 ...
Python 3.6.4 :: Anaconda, Inc.
installing: ca-certificates-2017.08.26-h1d4fec5_0 ...
installing

In [4]:
!conda env create --file local_env.yml

Solving environment: - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done




In [4]:
!source activate local_nmt && python sanity_check.py 1d

Traceback (most recent call last):
  File "sanity_check.py", line 24, in <module>
    from utils import batch_iter
  File "/content/drive/My Drive/cs224n/assignments/a4/utils.py", line 20, in <module>
    import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'


In [ ]:
!source activate local_nmt && python sanity_check.py 1e

In [ ]:
!source activate local_nmt && python sanity_check.py 1f

In [5]:
!source activate local_nmt && sh run.sh vocab

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
read in source sentences: ./chr_en_data/train.chr
read in target sentences: ./chr_en_data/train.en
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: ./chr_en_data/train.chr
  input_format: 
  model_prefix: src
  model_type: UNIGRAM
  vocab_size: 21000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: 

In [ ]:
!source activate local_nmt && sh run.sh train_local

In [10]:
!pip install -r gpu_requirements.txt

    100% |████████████████████████████████| 51kB 5.5MB/s 
  Cache entry deserialization failed, entry ignored
    100% |████████████████████████████████| 512kB 2.4MB/s 
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
    100% |████████████████████████████████| 61kB 10.4MB/s 
    99% |████████████████████████████████| 804.1MB 59.6MB/s eta 0:00:01tcmalloc: large alloc 1608187904 bytes == 0x56112175e000 @  0x7fa2301861e7 0x5610e83eb804 0x5610e8430eb4 0x5610e84e0ae2 0x5610e8431999 0x7fa22ceeaf98 0x5610e8412060 0x5610e843ff24 0x5610e849fbec 0x5610e84c4eb1 0x5610e84989a6 0x5610e8499a11 0x5610e849fcc5 0x5610e84c419a 0x5610e84997db 0x5610e849fcc5 0x5610e84c419a 0x5610e84989a6 0x5610e8499a11 0x5610e849fcc5 0x5610e84c4eb1 0x5610e84989a6 0x5610e8499eee 0x5610e841239f 0x5610e8416ff3 0x5610e8411dde 0x5610e8507095 0x5610e84121bb 0x5610e849fd3e 0x5610e84c419a 0x5610e84997db
    100% |████████████████████████████████| 804.1MB 1.8kB/s 
  Cache ent

In [48]:
!sh run.sh train

begin Maximum Likelihood training
epoch 1, iter 10, avg. loss 208.18, avg. ppl 3267.01 cum. examples 320, speed 5340.95 words/sec, time elapsed 1.54 sec
epoch 1, iter 20, avg. loss 178.23, avg. ppl 768.76 cum. examples 640, speed 5326.36 words/sec, time elapsed 3.15 sec
Traceback (most recent call last):
  File "run.py", line 360, in <module>
    main()
  File "run.py", line 352, in main
    train(args)
  File "run.py", line 185, in train
    loss.backward()
  File "/usr/local/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
KeyboardInterrupt
^C


In [21]:
!sh run.sh test

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
load test source sentences from [./chr_en_data/test.chr]
load test target sentences from [./chr_en_data/test.en]
load model from model.bin
Decoding: 100% 1000/1000 [00:53<00:00, 21.17it/s]
Corpus BLEU: 12.375868704793024


In [39]:
!python abc.py

tensor([[[1],
         [2],
         [0]],

        [[3],
         [0],
         [0]],

        [[4],
         [5],
         [6]]])
tensor([[[1],
         [2],
         [0]],

        [[3],
         [0],
         [0]],

        [[4],
         [5],
         [6]]])
tensor([[[True],
         [True],
         [True]],

        [[True],
         [True],
         [True]],

        [[True],
         [True],
         [True]]])
